=== RokKos/Izprasevalnik/ShemaVprasanj.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- definition of simple elements -->
  <xs:element name="odgovor" type="xs:string"/>
  <xs:element name="vsebina" type="xs:string"/>
  <xs:element name="tezavnost" type="xs:positiveInteger"/>
  <!-- <xs:element name="datum_lekcije" type="xs:date"/> -->

  <!-- definition of complex elements -->
  <xs:element name="vprasanje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="vsebina"/>
        <xs:element  ref="odgovor" maxOccurs="unbounded" minOccurs="1"/>
        <xs:element ref="tezavnost" minOccurs="0"/>
        <!--<xs:element ref="datum_lekcije" minOccurs="0"/> -->
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="poglavje">
    <xs:complexType>
      <xs:sequence>
        <xs:element  ref="vprasanje" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="predmet">
    <xs:complexType>
      <xs:sequence>
        <xs:element  ref="poglavje" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="letnik">
    <xs:complexType>
      <xs:sequence>
        <xs:element  ref="predmet" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Vprasanja">
    <xs:complexType>
      <xs:sequence>
        <xs:element  ref="letnik" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== RokKos/Izprasevalnik/Vprasanja.xml
<?xml version="1.0" encoding="UTF-8"?>
<Vprasanja xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ShemaVprasanj.xsd">
  <letnik>2
    <predmet>
      Kombinatorika
      <poglavje>
        Testno
        <vprasanje>
          Neki
          <vsebina>Test 1</vsebina>
          <odgovor>Test odgovor 1</odgovor>
          <tezavnost>1</tezavnost>
        </vprasanje>
        <vprasanje>
          Neki2
          <vsebina>Test 2</vsebina>
          <odgovor>Test odgovor 2</odgovor>
          <tezavnost>2</tezavnost>
        </vprasanje>
        <vprasanje>
          Neki3
          <vsebina>Test 3</vsebina>
          <odgovor>Test odgovor 3</odgovor>
          <tezavnost>3</tezavnost>
        </vprasanje>
      </poglavje>
    </predmet>
  </letnik>
</Vprasanja>
